#!/usr/bin/env python3
r"""Exact gain-graph search for regular groups in the Moore graph construction.

The normalized instance has q = |H| vertices (the branches 2,...,k, where
k=q+1).  An oriented edge ij receives a nonidentity gain g_ij, with
g_ji=g_ij^{-1}.  Every vertex row is a permutation of H\{e}; triangle and
quadrilateral gains must be nonidentity.

The first row is fixed to the canonical ordering of H\{e}.  The solver is a
complete finite-domain backtracker with MRV, row-AllDifferent propagation,
and eager checks of every newly completed triangle and quadrilateral.  The
abelian obstruction is an optional exact presolver; --skip-abelian-obstruction
forces actual enumeration (useful for the C6 smoke test).
"""

from __future__ import annotations

import argparse
import itertools
import json
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable, Sequence

import numpy as np


HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(REPO))

from harness.verify import VerificationFailure, verify_moore  # noqa: E402


class FiniteGroup:
    """Small finite group represented by a multiplication table."""

    def __init__(
        self,
        name: str,
        elements: Sequence[tuple[int, ...]],
        mul_table: Sequence[Sequence[int]],
        identity: int = 0,
    ) -> None:
        self.name = name
        self.elements = tuple(elements)
        self.mul_table = tuple(tuple(row) for row in mul_table)
        self.identity = identity
        self.order = len(elements)
        assert identity == 0, "the search assumes identity index zero"
        assert len(self.mul_table) == self.order
        self.inverse = tuple(self._find_inverse(a) for a in range(self.order))
        self.abelian = all(
            self.mul(a, b) == self.mul(b, a)
            for a in range(self.order)
            for b in range(self.order)
        )
        self._validate()
        self.derived_subgroup = self._derived_subgroup()

    def mul(self, a: int, b: int) -> int:
        return self.mul_table[a][b]

    def _find_inverse(self, a: int) -> int:
        for b in range(self.order):
            if self.mul(a, b) == 0 and self.mul(b, a) == 0:
                return b
        raise ValueError(f"no inverse for element {a}")

    def _validate(self) -> None:
        q = self.order
        expected = set(range(q))
        for a in range(q):
            assert set(self.mul_table[a]) == expected
            assert self.mul(0, a) == self.mul(a, 0) == a
        # These groups have order at most 56, so a full associativity check is
        # cheap and protects the certificate builder from a bad table.
        for a in range(q):
            for b in range(q):
                ab = self.mul(a, b)
                for c in range(q):
                    assert self.mul(ab, c) == self.mul(a, self.mul(b, c))

    def _derived_subgroup(self) -> frozenset[int]:
        """Return the subgroup generated by all commutators."""
        subgroup = {0}
        for a in range(self.order):
            for b in range(self.order):
                commutator = self.mul(
                    self.mul(self.inverse[a], self.inverse[b]),
                    self.mul(a, b),
                )
                subgroup.add(commutator)
        changed = True
        while changed:
            changed = False
            old = tuple(subgroup)
            for a in old:
                subgroup.add(self.inverse[a])
                for b in old:
                    subgroup.add(self.mul(a, b))
            if len(subgroup) != len(old):
                changed = True
        return frozenset(subgroup)

    def label(self, a: int) -> str:
        return str(self.elements[a])


def abelian_group(moduli: Sequence[int], name: str | None = None) -> FiniteGroup:
    moduli = tuple(moduli)
    elements = tuple(itertools.product(*(range(m) for m in moduli)))
    index = {x: i for i, x in enumerate(elements)}
    table = [
        [
            index[tuple((x + y) % m for x, y, m in zip(a, b, moduli))]
            for b in elements
        ]
        for a in elements
    ]
    group_name = name or " x ".join(f"Z{m}" for m in moduli)
    return FiniteGroup(group_name, elements, table)


def symmetric_group_3() -> FiniteGroup:
    elements = tuple(itertools.permutations(range(3)))
    index = {x: i for i, x in enumerate(elements)}

    def compose_right(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
        # p*q means apply p, then q.  Thus right multiplication composes in
        # the same left-to-right order as a walk's gains.
        return tuple(q[p[x]] for x in range(3))

    table = [[index[compose_right(a, b)] for b in elements] for a in elements]
    return FiniteGroup("S3", elements, table)


def get_group(key: str) -> FiniteGroup:
    groups = {
        "z2": lambda: abelian_group((2,), "Z2"),
        "z6": lambda: abelian_group((6,), "Z6"),
        "s3": symmetric_group_3,
        "h1": lambda: abelian_group((4, 2, 7), "Z4 x Z2 x Z7"),
        "h2": lambda: abelian_group((2, 2, 2, 7), "Z2^3 x Z7"),
    }
    try:
        return groups[key]()
    except KeyError as exc:
        raise ValueError(f"unknown group {key!r}; choose {', '.join(groups)}") from exc


@dataclass
class SearchStats:
    status: str = "UNKNOWN"
    reason: str = ""
    nodes: int = 0
    backtracks: int = 0
    domain_wipeouts: int = 0
    hall_union_failures: int = 0
    max_depth: int = 0
    free_edges: int = 0
    fixed_edges: int = 0
    elapsed_seconds: float = 0.0
    first_row_order: tuple[int, ...] = ()


class Timeout(Exception):
    pass


class GainSearch:
    """Complete DFS for (V), (T), and (Q), after first-row fixing."""

    def __init__(self, group: FiniteGroup, timeout: float | None = None) -> None:
        self.group = group
        self.q = group.order
        self.timeout = timeout
        self.deadline = None if timeout is None else time.monotonic() + timeout
        self.gain = [[-1] * self.q for _ in range(self.q)]
        self.used = [0] * self.q
        self.unassigned: set[tuple[int, int]] = set()
        self.stats = SearchStats(
            free_edges=(self.q - 1) * (self.q - 2) // 2,
            fixed_edges=self.q - 1,
            first_row_order=tuple(range(1, self.q)),
        )
        self.started = 0.0

        # Sound symmetry break: at vertex 0 the outgoing gains are a bijection
        # to H\{e}; permuting the other q-1 vertices realizes this order.
        for j, value in enumerate(range(1, self.q), start=1):
            self._place(0, j, value)
        for i in range(1, self.q):
            for j in range(i + 1, self.q):
                self.unassigned.add((i, j))

    def _place(self, i: int, j: int, value: int) -> None:
        inv = self.group.inverse[value]
        assert self.gain[i][j] == self.gain[j][i] == -1
        assert not (self.used[i] >> value) & 1
        assert not (self.used[j] >> inv) & 1
        self.gain[i][j] = value
        self.gain[j][i] = inv
        self.used[i] |= 1 << value
        self.used[j] |= 1 << inv

    def _remove(self, i: int, j: int, value: int) -> None:
        inv = self.group.inverse[value]
        self.gain[i][j] = self.gain[j][i] = -1
        self.used[i] &= ~(1 << value)
        self.used[j] &= ~(1 << inv)

    def _product(self, values: Iterable[int]) -> int:
        product = 0
        for value in values:
            product = self.group.mul(product, value)
        return product

    def _candidate_ok(self, i: int, j: int, value: int) -> bool:
        inv = self.group.inverse[value]
        if (self.used[i] >> value) & 1 or (self.used[j] >> inv) & 1:
            return False

        self.gain[i][j], self.gain[j][i] = value, inv
        try:
            # Every completed triangle containing ij.
            for a in range(self.q):
                if a in (i, j):
                    continue
                if self.gain[j][a] >= 0 and self.gain[a][i] >= 0:
                    if self._product((value, self.gain[j][a], self.gain[a][i])) == 0:
                        return False

            # Every completed simple 4-cycle containing the directed edge ij.
            others = [a for a in range(self.q) if a not in (i, j)]
            for a in others:
                if self.gain[j][a] < 0:
                    continue
                for b in others:
                    if b == a:
                        continue
                    if self.gain[a][b] >= 0 and self.gain[b][i] >= 0:
                        if self._product(
                            (value, self.gain[j][a], self.gain[a][b], self.gain[b][i])
                        ) == 0:
                            return False
            return True
        finally:
            self.gain[i][j] = self.gain[j][i] = -1

    def _domain(self, edge: tuple[int, int]) -> list[int]:
        i, j = edge
        return [value for value in range(1, self.q) if self._candidate_ok(i, j, value)]

    def _select_edge(self) -> tuple[tuple[int, int], list[int]] | None:
        best_edge = None
        best_domain: list[int] | None = None
        domains: dict[tuple[int, int], list[int]] = {}

        for edge in sorted(self.unassigned):
            domain = self._domain(edge)
            domains[edge] = domain
            if not domain:
                self.stats.domain_wipeouts += 1
                return edge, domain
            if best_domain is None or len(domain) < len(best_domain):
                best_edge, best_domain = edge, domain
                if len(domain) == 1:
                    break

        if best_edge is None:
            return None

        # Cheap Hall check for each row: the union of the possible outgoing
        # symbols on its remaining edges must be large enough.  Because each
        # row has exactly as many unused symbols as unfilled cells, this often
        # detects failure before a domain itself empties.
        for v in range(1, self.q):
            row_edges = [edge for edge in self.unassigned if v in edge]
            if not row_edges:
                continue
            union = 0
            for edge in row_edges:
                domain = domains.get(edge)
                if domain is None:
                    domain = self._domain(edge)
                    domains[edge] = domain
                i, _ = edge
                if v == i:
                    for value in domain:
                        union |= 1 << value
                else:
                    for value in domain:
                        union |= 1 << self.group.inverse[value]
            if union.bit_count() < len(row_edges):
                self.stats.hall_union_failures += 1
                return best_edge, []

        return best_edge, best_domain

    def _dfs(self, depth: int) -> bool:
        if self.deadline is not None and time.monotonic() >= self.deadline:
            raise Timeout
        self.stats.max_depth = max(self.stats.max_depth, depth)
        selected = self._select_edge()
        if selected is None:
            return True
        edge, domain = selected
        if not domain:
            self.stats.backtracks += 1
            return False

        i, j = edge
        self.unassigned.remove(edge)
        try:
            for value in domain:
                self.stats.nodes += 1
                self._place(i, j, value)
                if self._dfs(depth + 1):
                    return True
                self._remove(i, j, value)
            self.stats.backtracks += 1
            return False
        finally:
            # On SAT the selected edge remains placed, but it is no longer an
            # unassigned edge.  On UNSAT/timeout all placements were removed.
            if self.gain[i][j] < 0:
                self.unassigned.add(edge)

    def solve(self) -> tuple[list[list[int]] | None, SearchStats]:
        self.started = time.monotonic()
        try:
            sat = self._dfs(0)
            self.stats.status = "SAT" if sat else "UNSAT"
            self.stats.reason = "complete DFS witness" if sat else "complete DFS exhaustion"
        except Timeout:
            self.stats.status = "UNKNOWN"
            self.stats.reason = "wall-clock timeout"
            sat = False
        self.stats.elapsed_seconds = time.monotonic() - self.started
        solution = [row[:] for row in self.gain] if sat else None
        return solution, self.stats


def quotient_obstruction(group: FiniteGroup) -> str | None:
    r"""Return the exact abelianization no-go for a nonperfect H, |H| > 2.

    For endpoints a,b with gain t and each other vertex i, put x_i=g_ai,
    y_i=g_ib, z_i=x_i*y_i.  (V), (T), and (Q) say that each of x, y, z is a
    permutation of H\{e,t}.  Map to the abelianization A=H/[H,H].  Multiplying
    each list in A gives P/t = (P/t)^2, hence the image of t is P.  This holds
    for every t != e.  If P != e the quotient map is injective and |H| <= 2;
    if P=e the abelianization is trivial.  Therefore H must be perfect (or C2).
    """
    if group.order > 2 and len(group.derived_subgroup) < group.order:
        return (
            "abelianization partial-transversal obstruction: (V),(T),(Q) require "
            "H to be perfect (or H=C2), but [H,H] has order "
            f"{len(group.derived_subgroup)} < {group.order}"
        )
    return None


def validate_assignment(group: FiniteGroup, gain: Sequence[Sequence[int]]) -> None:
    q = group.order
    nonidentity = set(range(1, q))
    assert len(gain) == q
    for i in range(q):
        assert gain[i][i] == -1
        assert set(gain[i][j] for j in range(q) if j != i) == nonidentity
        for j in range(q):
            if i != j:
                assert group.mul(gain[i][j], gain[j][i]) == 0

    for i, j, k in itertools.permutations(range(q), 3):
        assert group.mul(group.mul(gain[i][j], gain[j][k]), gain[k][i]) != 0
    for i, j, k, ell in itertools.permutations(range(q), 4):
        product = group.mul(
            group.mul(group.mul(gain[i][j], gain[j][k]), gain[k][ell]),
            gain[ell][i],
        )
        assert product != 0


def build_moore_adjacency(group: FiniteGroup, gain: Sequence[Sequence[int]]) -> np.ndarray:
    """Expand a complete gain assignment to the (q+1)^2+1 graph."""
    validate_assignment(group, gain)
    q = group.order
    k = q + 1
    n = k * k + 1
    A = np.zeros((n, n), dtype=np.uint8)

    def connect(a: int, b: int) -> None:
        assert a != b and A[a, b] == 0
        A[a, b] = A[b, a] = 1

    root = 0
    neighbor = lambda block: 1 + block
    leaf = lambda block, x: 1 + k + block * q + x

    for block in range(k):
        connect(root, neighbor(block))
        for x in range(q):
            connect(neighbor(block), leaf(block, x))

    for left in range(k):
        for right in range(left + 1, k):
            h = 0 if left == 0 else gain[left - 1][right - 1]
            for x in range(q):
                y = group.mul(x, h)
                connect(leaf(left, x), leaf(right, y))
    return A


def write_witness(path: Path, group: FiniteGroup, gain: Sequence[Sequence[int]]) -> None:
    payload = {
        "group": group.name,
        "elements": [list(x) for x in group.elements],
        "gain_indices": gain,
        "gain_elements": [
            [None if value < 0 else list(group.elements[value]) for value in row]
            for row in gain
        ],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")


def solve_one(
    key: str,
    timeout: float | None,
    skip_obstruction: bool,
    witness_path: Path | None,
    verify_graph: bool,
) -> tuple[str, SearchStats, list[list[int]] | None]:
    group = get_group(key)
    obstruction = None if skip_obstruction else quotient_obstruction(group)
    if obstruction:
        stats = SearchStats(
            status="UNSAT",
            reason=obstruction,
            free_edges=(group.order - 1) * (group.order - 2) // 2,
            fixed_edges=group.order - 1,
            first_row_order=tuple(range(1, group.order)),
        )
        solution = None
    else:
        solution, stats = GainSearch(group, timeout=timeout).solve()

    verified = "not run"
    if solution is not None:
        validate_assignment(group, solution)
        if witness_path is not None:
            write_witness(witness_path, group, solution)
        if verify_graph:
            A = build_moore_adjacency(group, solution)
            verify_moore(A, group.order + 1, verbose=True)
            verified = "PASS"

    print(json.dumps({
        "group_key": key,
        "group": group.name,
        "order": group.order,
        "abelian": group.abelian,
        "stats": asdict(stats),
        "verify_moore": verified,
        "witness": str(witness_path) if solution is not None and witness_path else None,
    }, indent=2))
    return stats.status, stats, solution


def run_smoke(output_dir: Path) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    cases = (
        ("z2", False, True),
        # Deliberately skip the quotient theorem here: these must be
        # independent complete search/exhaustion smoke tests.
        ("z6", True, False),
        ("s3", True, True),
    )
    expected = {"z2": "SAT", "z6": "UNSAT"}
    summary = {}
    for key, skip_obstruction, verify_graph in cases:
        print(f"=== smoke {key} ===")
        path = output_dir / f"{key}_witness.json"
        status, stats, solution = solve_one(
            key,
            timeout=None,
            skip_obstruction=skip_obstruction,
            witness_path=path,
            verify_graph=verify_graph,
        )
        summary[key] = {
            "status": status,
            "stats": asdict(stats),
            "verify_moore": "PASS" if solution is not None and verify_graph else "not applicable",
            "witness": str(path) if solution is not None else None,
        }
        if key in expected and status != expected[key]:
            raise AssertionError(f"smoke {key}: got {status}, expected {expected[key]}")
    (output_dir / "smoke_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    smoke = sub.add_parser("smoke", help="run all mandatory small cases")
    smoke.add_argument("--output-dir", type=Path, default=HERE / "runs")

    solve = sub.add_parser("solve", help="solve one named group")
    solve.add_argument("--group", required=True, choices=("z2", "z6", "s3", "h1", "h2"))
    solve.add_argument("--timeout", type=float, default=None)
    solve.add_argument("--skip-abelian-obstruction", action="store_true")
    solve.add_argument("--witness", type=Path, default=None)
    solve.add_argument("--verify-graph", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.command == "smoke":
            return run_smoke(args.output_dir)
        status, _, _ = solve_one(
            args.group,
            timeout=args.timeout,
            skip_obstruction=args.skip_abelian_obstruction,
            witness_path=args.witness,
            verify_graph=args.verify_graph,
        )
        return 0 if status in ("SAT", "UNSAT") else 2
    except VerificationFailure as exc:
        print(f"verification failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
